version: '3.7'
services:
  app:
    build: .
    environment:
      - LANG=C.UTF-8
    ports:
      - 11025:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/react-tutorial
      - /opt/react-tutorial/node_modules
